### ISSUE TITLE
Students contributing to cheatsheet

### ISSUE THREAD

**Issue by ameetmadan** [xzyaoi/uzh-info2-cheatsheet#1]
Hi,

First of all, thanks for creating this cheat sheet. I am sure it will be an invaluable resource for the exam preparation. Is it intended, that students can create PR's or is it only limited to TA's? 

Thanks and best regards,
Ameet

**Comment by qingchen3** [comment]
Hi Ameet,

Students of Informatics-II are more than welcome to contribute to this cheatsheet.

Best regards,
Qing
